apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rlsv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-rlsv@sha256:4c1a1c02db25f9dbb9aab4fa2e851d81fc74949402bb5096eed22ad8a94f6286
        name: my-nodejs
        resources: {}
status: {}
